esphome:
  name: lcd16x2
  friendly_name: Two Line LCD

esp32:
  board: esp32-c3-devkitm-1

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LCD16x2"
    password: !secret wifi_ap_password

captive_portal:

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - GPIO5
      - GPIO4
      - GPIO3
      - GPIO2
    enable_pin: GPIO6
    rw_pin: GPIO7
    rs_pin: GPIO21
    #lambda: |-
      //it.print("Hello World!");
      // Print 0 at the top left
      //it.print("0");

      // Print 1 at the second row and second column.
      //it.print(1, 1, "1");

      // Let's write a sensor value (let's assume it's 42.1)
      //it.printf("%.1f", id(my_sensor).state);
      // Result: "42.1" (the dot will appear on the segment showing "2")

      // Print a right-padded sensor value with 0 digits after the decimal
      //it.printf("Sensor value: %8.0f", id(my_sensor).state);
      // Result: "Sensor value:       42"

      // Print the current time
      //it.strftime("It is %H:%M on %d.%m.%Y", id(myTime).now());
      // Result for 10:06 on august 21st 2018 -> "It is 10:06 on 21.08.2018"
    user_characters:
      - position: 0
        data:
          - 0b00000
          - 0b01010
          - 0b00000
          - 0b00100
          - 0b00100
          - 0b10001
          - 0b01110
          - 0b00000
      - position: 7
        data:
          - 0b00000
          - 0b01010
          - 0b00000
          - 0b00100
          - 0b00100
          - 0b00000
          - 0b01110
          - 0b10001
    lambda: |-
      it.print("Hello, world \x08 \x07!");

# (Optional) For displaying time:
time:
- platform: homeassistant
  id: myTime
