esphome:
  name: people-sensor-0
  friendly_name: People Sensor

esp32:
  board: esp32-c3-devkitm-1

logger:
  level: VERBOSE

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "People Sensor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

i2c:
    sda: GPIO6  # BLU
    scl: GPIO7  # YEL
    scan: true
    id: bus_a
    frequency: 2000000.0  #### TODO try 4000000.0

sensor:
  - platform: sen21231
    id: person_sensor
